config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'welcome#index'

  resources :users
  resources :reset_passwords, only: [:new, :create, :edit, :update]
  resources :teams do
    get "invites"
    post "invites"
    resources :memberships
    resources :games, only: [:index, :create, :update, :destroy] do
      resources :rsvps, only: [:index, :show ,:update] do
        get "accept"
        get "decline"
      end
    end
  end

  resource :auth, only: [:new, :create, :destroy]
  get 'auth/facebook/callback', to: 'auths#facebook_auth'
  get 'auth/failure', to: redirect('/')

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/views/shared/_errors.html.erb
<div class="alert alert-danger" role="alert">
  <!-- <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> -->
  <% errors.each do |error| %>
    <div><%= error %></div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<!--<div class="wrapper-for-content-outside-of-footer">
   Uncomment this whole section for a sticky footer. The content of the page should be inside of this .wrapper-for-content-outside-of-footer
</div>-->

<footer class="footer-2" role="contentinfo">
  <div class="footer-logo">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
    <ul>
      <li><a href="javascript:void(0)">Designed and developed by Oivat Consulting</a></li>
    </ul>

    <div class="footer-secondary-links">
      <ul>
        <li><a href="javascript:void(0)">Learn more about Oivat</a></li>
      </ul>

      <ul class="footer-social">
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png" alt="Facebook">
          </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">
        </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png" alt="YouTube">
        </a></li>
      </ul>
    </div>
</footer>

app/views/shared/_header.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo Image">
    </a>
    <nav role="navigation">
      <span class='header-title'><%= link_to "Team Genie", root_path, class: 'title' %></span>
    </nav>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">
      <span class='fa fa-bars fa-2x'></span>
    </a>
    <div class="navigation-tools">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if current_user %>
          <li class="nav-link">Welcome, <%= current_user.name %></li>
          <li class="nav-link"><%= link_to "New Team", new_team_path %></li>
          <li class="nav-link"><%= link_to "My Account", edit_user_path(current_user) %></li>
          <li class="nav-link"><%= link_to "Log out", auth_path(current_user), method: 'delete'%></li>
        <% else %>
          <li class="nav-link"><%= link_to "Sign up", new_user_path%></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>