config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'welcome#index'

  resources :users
  resources :reset_passwords, only: [:new, :create, :edit, :update]
  resources :teams do
    get "invites"
    post "invites"
    resources :memberships
    resources :games, only: [:index, :create, :update, :destroy] do
      resources :rsvps, only: [:index, :show ,:update] do
        get "accept"
        get "decline"
      end
    end
  end

  resource :auth, only: [:new, :create, :destroy]
  get 'auth/facebook/callback', to: 'auths#facebook_auth'
  get 'auth/failure', to: redirect('/')

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
	def create
    @user = User.find_by(email: params[:user][:email])
    if can_authenticate?
    	assign_cookie
      respond_to { |format| format.js { "window.location = /teams" } }
      # redirect_to teams_path
    else
    	@errors = error_message
      respond_to { |format| format.js { render nothing: true, status: 401 } }
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_path
  end

  def facebook_auth
    @user = User.from_facebook(env['omniauth.auth'])
    if @user
      assign_cookie
      redirect_to teams_path
    else
      @user = User.create_from_facebook(env['omniauth.auth'])
      assign_cookie
      redirect_to edit_user_path(@user)
    end
  end

  private 

  def remember_me?
  	params[:user] && params[:user][:remember_me] == '1'
  end

  def assign_cookie
  	if remember_me?
  	  cookies.permanent[:auth_token] = @user.auth_token
  	else
  	  cookies[:auth_token] = @user.auth_token
  	end
  end

  def can_authenticate?
  	@user && @user.authenticate(params[:user][:password])
  end

  def error_message
  	["Your email or password are incorrect.  Please try again"]
  end
end

app/views/auths/_new.html.erb
<div class='form'>
  <%= form_for :user, url: auth_path, role: 'form', remote: true do |f| %>
    <% if @errors %>
      <%= render partial: 'shared/errors', locals: { errors: @errors } %>
    <% end %>
    <%= f.email_field :email, autofocus: true, placeholder: "Email" %>
    <%= f.password_field :password, placeholder: "Password" %>
    <%# f.check_box :remember_me, text: "Remember me", checked: true %>
    <%= f.submit "Log In" %>
  <% end %>
  <a href="/auth/facebook" class="button button-facebook">
    <i class="fa fa-facebook fa-fx"></i> <span>Facebook</span>
  </a>

  <div class='other-functions'><%= link_to "Reset Password", new_reset_password_path %> | <%= link_to "Create Account", new_user_path %></div>
</div>