config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'welcome#index'

  resources :users
  resources :reset_passwords, only: [:new, :create, :edit, :update]
  resources :teams do
    get "invites"
    post "invites"
    resources :memberships
    resources :games, only: [:index, :create, :update, :destroy] do
      resources :rsvps, only: [:index, :show ,:update] do
        get "accept"
        get "decline"
      end
    end
  end

  resource :auth, only: [:new, :create, :destroy]
  get 'auth/facebook/callback', to: 'auths#facebook_auth'
  get 'auth/failure', to: redirect('/')

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    user.send_password_reset if user
    redirect_to root_url
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if token_expired? 
      redirect_to new_password_reset_path
    elsif @user.update_attributes(user_params)
      @user.save!(validate: false)
      redirect_to root_url(password_reset: true)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def token_expired?
    @user.password_reset_sent_at < 2.days.ago
  end

end

app/views/reset_passwords/edit.html.erb
<%= form_for @user, url: reset_password_path(params[:id]) do |f| %>

  <% if @error %>
    <div id="error_explanation">
      <% @error %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Reset Password", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/reset_passwords/new.html.erb
<div class="sub-pg-padding">
  <div class="row">
    <div class="col-md-8">
      <div class="well">
        <h4>Reset Your Password</h4>
        <hr />

        <%= form_tag reset_passwords_path, :method => :post, role: 'form' do |f|%>

          <% if @error %>
            <div id="error_explanation">
              <ul>
              <% @error.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <div class='control-label'><%= label_tag :email %></div>
            <%= text_field_tag :email, params[:email], class: 'form-control' %>
          </div>
          <div class="actions"><%= submit_tag "Reset Password", class: 'btn btn-primary' %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>